spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_qa?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root  # MySQL用户名
    password: 123456  # MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver



logging:
  level:
    com.health: debug
