spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_qa?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root  # MySQL用户名
    password: 123456  # MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver

#修改启动端口
server:
  port: 8080

ai:
  api:
    key: sk-7959fef721174706bc2d71c6080d4402

logging:
  level:
    com.health: debug
